
const masterList = [
    {
        category: "Apparel",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Shirt",
        price: "$15.00",
        qty: 5,
        id: '1',
    },
    {
        category: "Apparel",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Shirt",
        price: "$15.00",
        qty: 10,
        id: '2',
    },
    {
        category: "Vinyl",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Record",
        price: "$35.00",
        qty: 7,
        id: '3',
    },
    {
        category: "Vinyl",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Record",
        price: "$35.00",
        qty: 1,
        id: '4',
    },
    {
        category: "Digital",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Print",
        price: "$10.00",
        qty: 50,
        id: '5',
    },
    {
        category: "Digital",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Print",
        price: "$10.00",
        qty: 20,
        id: '6',
    },
    {
        category: "Accessories",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Key Chain",
        price: "$5.00",
        qty: 5,
        id: '7',
    },
    {
        category: "Accessories",
        imgSrc: "https://picsum.photos/200/300",
        imgAlt: "A Picture",
        description: "Key Chain",
        price: "$5.00",
        qty: 5,
        id: '8',
    }

];
export default masterList;